name: Build and Release Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --runtime linux-x64 --self-contained false -o publish/linux-x64
          dotnet publish --configuration Release --runtime osx-x64 --self-contained false -o publish/osx-x64
          dotnet publish --configuration Release --runtime win-x86 --self-contained false -o publish/win-x86
          dotnet publish --configuration Release --runtime win-x64 --self-contained false -o publish/win-x64
      
      - name: Create setup files
        if: matrix.os == 'windows-latest'
        run: |
          cd publish/win-x86
          choco pack
          cd ../win-x64
          choco pack
          
      - name: Create setup files
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd publish/linux-x64
          mkdir deb
          dotnet deb --output deb/ ./MyApp
          cd deb
          dpkg-deb --build MyApp
          cd ../..
          
      - name: Create setup files
        if: matrix.os == 'macos-latest'
        run: |
          cd publish/osx-x64
          hdiutil create -format UDZO -srcfolder MyApp.app MyApp.dmg
          cd ..
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }} 64x
          path: publish/${{ matrix.os }}-x64
          
      - name: Upload setup files
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Windows Setup Files
          path: publish/win-x86/*.nupkg, publish/win-x64/*.nupkg
          
      - name: Upload setup files
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu Setup Files
          path: publish/linux-x64/deb/MyApp.deb
          
      - name: Upload setup files
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: MacOS Setup Files
          path: publish/osx-x64/MyApp.dmg
          
