name: Build and Release Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --runtime linux-x64 --self-contained false -o publish/linux-x64
          dotnet publish --configuration Release --runtime osx-x64 --self-contained false -o publish/osx-x64
          dotnet publish --configuration Release --runtime win-x86 --self-contained false -o publish/win-x86
          dotnet publish --configuration Release --runtime win-x64 --self-contained false -o publish/win-x64
      
      - name: Create artifacts
        run: |
          mkdir -p artifacts
          cp -r publish/linux-x64 artifacts/MyApp-Linux-x64
          cp -r publish/osx-x64 artifacts/MyApp-OSX-x64
          cp -r publish/win-x86 artifacts/MyApp-Windows-x86
          cp -r publish/win-x64 artifacts/MyApp-Windows-x64
        working-directory: .
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-Artifacts
          path: artifacts/
